Fix: Filter providers based on viewport mobile
1Hive/gardens-ui pull request #801
Opened 2022-01-19 06:09 UTC by kamikazebr

Closes https://github.com/1Hive/gardens/issues/504

2022-01-19 14:49 UTC, tmoutinho reviewed
Left some comments.

2022-01-19 14:49 UTC, tmoutinho commented on src/ethereum-providers/connectors.ts
> -].filter(p => p)
Same comment as above.

2022-01-20 02:17 UTC, kamikazebr commented on src/ethereum-providers/connectors.ts
> +export const CONNECTORS_MOBILE = CONNECTORS.filter(
Excelent idea!

2022-01-20 02:21 UTC, kamikazebr commented on src/providers/Wallet.js
> +import { useViewport } from '@1hive/1hive-ui'
I tried, that thing got wild! Alot files need be changed too to do it. So i keep it simple.

While was converting thats files to Typescript i got alot weirds stuffs. For example a method connect() need 1 argument but was been called with 0 args and alots another things. 

Maybe we create new PR for it?

2022-01-20 02:23 UTC, kamikazebr commented on src/components/Account/ScreenProviders.js
>    textStyle,
Yah that i think its more possible to do, will check

2022-01-20 02:35 UTC, kamikazebr commented on src/ethereum-providers/connectors.ts
> +export const CONNECTORS_MOBILE = CONNECTORS.filter(
BTW I really dont know why it need be there, that filter, maybe to remove the null PORTIS when it was javascript file. Almost sure it not more necessary

2022-01-20 03:00 UTC, kamikazebr commented on src/components/Account/ScreenProviders.js
>    textStyle,
Done

2022-01-20 03:03 UTC, kamikazebr commented on src/components/Account/ScreenProviders.tsx
> +    name: string
Its need be optional, required by other lib

2022-01-20 03:05 UTC, kamikazebr commented on src/components/Account/ScreenProviders.tsx
> +      )}
Provider now can be undefined, here i choose just not show anything while provider its not defined.

Using 'if else' with message for example "Provider not found" could lead to flickering the UI.

2022-01-20 03:06 UTC, kamikazebr commented on src/ethereum-providers/connectors.ts
> +    [key: string]: any
Strong types already knowed but with dynamic to ensure it now will break anything

2022-01-20 03:21 UTC, kamikazebr commented on src/ethereum-providers/connectors.ts
> +  })
Extract that IF to correct the return type. it was retuning union with null and getting errors on other file use that.

2022-01-29 22:36 UTC, tmoutinho approved these changes
✌️

2022-02-18 22:05 UTC, 0xGabi requested changes
LGTM!

2022-02-18 22:05 UTC, 0xGabi approved these changes

2022-02-18 22:05 UTC, merged